#!/bin/zsh
# This file is sourced rather than run, so the shebang is only here to stop
# editors and linters treating it as bash and flagging the zsh-only syntax.

# See also .zshenv, which gets run before .zshrc to set environment variables.
# That sets up the path, including homebrew and mise.

# ------------------------------------------------------------------------------------------
# Configure completion.
#
# compinit's security audit of every directory in fpath costs ~25ms, so skip it
# with -C and do one full run a day to pick up newly installed completions.
#
# The glob qualifiers match .zcompdump only if it exists (N), is a regular file
# (.), and was last modified less than 24 hours ago (mh-24). A non-empty match
# means the dump is fresh enough to trust.

autoload -Uz compinit
fresh_zcompdump=($HOME/.zcompdump(N.mh-24))
if (( $#fresh_zcompdump )) {
  compinit -C
} else {
  compinit
}
unset fresh_zcompdump

if [[ -x $HOMEBREW_PREFIX/bin/fzf ]] {
  source <(fzf --zsh)
  export FZF_DEFAULT_COMMAND='fd --type f'

  if [[ -d $HOME/.config/zsh/plugins/fzf-tab ]] {
    # Use fzf as a completion menu for everything. This needs to load after
    # compinit, but before other plugins.
    source $HOME/.config/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
  }
}

# ------------------------------------------------------------------------------------------
# Configure syntax highlighting.
#
# https://github.com/zsh-users/zsh-syntax-highlighting

if [[ -d $HOMEBREW_PREFIX/share/zsh-syntax-highlighting ]] {
  source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
}

# ------------------------------------------------------------------------------------------
# Configure zoxide.

if [[ -x $HOMEBREW_PREFIX/bin/zoxide ]] {
  eval "$(zoxide init zsh)"
}

# ------------------------------------------------------------------------------------------
# Configure opam (OCaml).

if [[ -f ~/.opam/opam-init/init.zsh ]] {
  source ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null
}

# ------------------------------------------------------------------------------------------
# Set shell options.

unsetopt beep # Don't beep on errors.
bindkey -v    # Use vim keybindings.
KEYTIMEOUT=1  # Allow key sequences to be recognized faster.

# ------------------------------------------------------------------------------------------
# Configure history.

HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY        # Share history between active sessions.
setopt HIST_IGNORE_ALL_DUPS # Keep only the most recent copy of a command.
setopt HIST_REDUCE_BLANKS   # Remove leading/trailing whitespace from commands.

# ------------------------------------------------------------------------------------------
# Use Pure to set up the prompt.
#
# https://github.com/sindresorhus/pure

autoload -U promptinit && promptinit
# Show a symbol when there's stuff stashed.
zstyle :prompt:pure:git:stash show yes
# Don't do git fetches for me, coz I'd rather not have 1Password prompts popping up randomly.
export PURE_GIT_PULL=0
prompt pure

# ------------------------------------------------------------------------------------------
# Set flags for a couple of tools.

export CLICOLOR=1        # Make ls colour its output.
export EZA_ICONS_AUTO=1  # Show icons in eza.
export LESS=-R           # Make less support ANSI colour sequences.

# ------------------------------------------------------------------------------------------
# Set aliases.

alias ls='eza'

alias be='bundle exec'
alias br='./bin/rails'

alias cdr='cd $(git root)'

alias ga='git add'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gff='git merge --ff-only'
alias gl='git log'
alias gm='git merge --no-ff'
alias gp='git push'
alias gpr='git push -u && gh pr create --web'
alias gb='gh pr view --web'
alias gs='git status'

alias zed='/usr/local/bin/zed'

alias mvim='NVIM_APPNAME=nvim-up-starter nvim'
alias tvim='NVIM_APPNAME=nvim-test nvim'

function autonode { echo $1 | entr -c node $1 }
function autoruby { echo $1 | entr -c ruby $1 }
function autorspec { echo $1 | entr -c ./up rspec $1 }

alias sup='./up start up_native'

alias esp='source ~/esp/esp-idf/export.sh'
